#!/bin/bash
# H2: SDD Upstream Artifact Immutability Guard
# Hook type: PreToolUse (Edit, Write) | Timeout: 5s
# Enforces Art. 4 of the SDD Constitution: downstream skills cannot modify upstream artifacts.
#
# Immutability table (when stage X is running, these paths are PROHIBITED):
#   test-planner       → requirements/, spec/, audits/
#   plan-architect     → requirements/, spec/, audits/, test/
#   task-generator     → requirements/, spec/, audits/, test/, plan/
#   task-implementer   → requirements/, spec/, audits/, test/, plan/, task/
#
# Exceptions:
#   - spec-auditor (Mode Fix): spec/ is allowed (by design)
#   - task-implementer: Edit on task/TASK-FASE-*.md is allowed (checkbox updates)
#                       Write on task/* is blocked (full overwrite protection)
#                       test/* is allowed when it is implementation code declared in the SDD Stack
#                       Profile of CLAUDE.md (code_paths/test_paths, e.g. Rails Minitest `test` at
#                       repo root); top-level test/*.md (TEST-PLAN.md, TEST-MATRIX-*...) stays denied
#   - req-change running: requirements/ and spec/ are allowed (lateral skill), even when a
#     downstream stage is also running
#   - Several stages running: the most downstream linear stage applies (pipeline order)
#   - Always allowed (infrastructure, not pipeline artifacts): pipeline-state.json, .sdd/*,
#     changes/*, feedback/*, .claude/hooks/*, .claude/settings*.json, .claude/agents/*,
#     .claude/sdd/*, .claude/sdd-sessions.json
#   - No pipeline-state.json or no running stage: permissive mode (allow all)
#   - Always denied, whatever the state (generated by the sdd CLI, never edited by hand):
#     acceptance/decisions.jsonl (human decisions: `sdd accept record`, which the tool guard makes ask),
#     acceptance/challenges.jsonl (adversarial findings: `sdd accept challenge add`, validated evidence)
#     and acceptance/ACCEPTANCE-REPORT.md (`sdd accept --report`). This prevents accidental self-approval
#     through a file edit; it is not a guarantee (Bash can still write the file).
#
# Dos raíces (hooks/lib/sdd-common.sh): REL_PATH es relativo al toplevel git del FICHERO
# (worktrees externos, claude -w y .claude/worktrees/x quedan cubiertos); pipeline-state.json
# se lee de STATE_ROOT (raíz del .git común).
#
# Con rol (SDD_ROLE o registro de sesiones) presente en .claude/sdd-sessions.json:
#   (a) REL_PATH fuera de `owns` del rol → deny, haya o no stage running.
#   (b) el stage running que aplica es el más downstream de los `stages` del rol.
#   (c) el resto de reglas de inmutabilidad se aplica igual.
# Sin rol o sin registro → comportamiento anterior.

set -euo pipefail

SDD_LIB="$(dirname "${BASH_SOURCE[0]}")/lib/sdd-common.sh"
if [ ! -f "$SDD_LIB" ]; then echo "sdd-upstream-guard: falta $SDD_LIB" >&2; exit 0; fi
# shellcheck source=lib/sdd-common.sh
. "$SDD_LIB"

INPUT=$(cat)

# Extract tool_name and file_path from hook input
TOOL_NAME=$(printf '%s' "$INPUT" | sdd_json_get - '.tool_name // .toolName // empty') || TOOL_NAME=""
FILE_PATH=$(printf '%s' "$INPUT" | sdd_json_get - '.toolInput.file_path // .tool_input.file_path // empty') || FILE_PATH=""

# If we can't determine the file path, allow
if [ -z "$FILE_PATH" ]; then
  exit 0
fi

sdd_roots "$INPUT" "$FILE_PATH"
PIPELINE_STATE="$STATE_ROOT/pipeline-state.json"

# Not under the project: allow
case "$REL_PATH" in
  /*|[A-Za-z]:/*) exit 0 ;;
esac

deny() {
  local escaped
  escaped=$(sdd_json_string "$1")
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":%s}}\n' "$escaped"
  exit 0
}

# Generated acceptance files: only the sdd CLI writes them
case "$REL_PATH" in
  acceptance/decisions.jsonl)
    deny "SDD acceptance: acceptance/decisions.jsonl holds human decisions tied to the requirement text. Append one with \`node \"\$SDD_PLUGIN_ROOT/scripts/sdd.mjs\" accept record …\` after the person has confirmed it; never edit the file." ;;
  acceptance/challenges.jsonl)
    deny "SDD acceptance: acceptance/challenges.jsonl holds the adversarial round's findings, anchored to HEAD and to the requirement text. Add one with \`node \"\$SDD_PLUGIN_ROOT/scripts/sdd.mjs\" accept challenge add …\` (it validates the evidence); a person dismisses one with \`accept record challenge-dismissal\`. Never edit the file." ;;
  acceptance/ACCEPTANCE-REPORT.md)
    deny "SDD acceptance: acceptance/ACCEPTANCE-REPORT.md is generated. Regenerate it with \`node \"\$SDD_PLUGIN_ROOT/scripts/sdd.mjs\" accept --report acceptance/ACCEPTANCE-REPORT.md\`." ;;
esac

# Always allowed: infrastructure and lateral directories
case "$REL_PATH" in
  pipeline-state.json|.sdd/*|changes/*|feedback/*) exit 0 ;;
  .claude/hooks/*|.claude/settings*.json|.claude/agents/*|.claude/sdd/*|.claude/sdd-sessions.json) exit 0 ;;
esac

# Role (optional): ownership by path pattern
ROLE=$(sdd_role) || ROLE=""
ROLE_STAGES=""
if [ -n "$ROLE" ] && sdd_role_exists "$ROLE"; then
  OWNS=$(sdd_role_owns "$ROLE") || OWNS=""
  if ! sdd_globs_match "$REL_PATH" "$OWNS"; then
    OWNS_FLAT=$(printf '%s' "$OWNS" | tr '\n' ' ')
    deny "Rol $ROLE no posee $REL_PATH (owns: ${OWNS_FLAT% })"
  fi
  ROLE_STAGES=$(sdd_role_stages "$ROLE") || ROLE_STAGES=""
else
  ROLE=""
fi

# If no pipeline-state.json, permissive mode
if [ ! -f "$PIPELINE_STATE" ]; then
  exit 0
fi

# Running stages: linear stages in pipeline order (upstream → downstream), then lateral ones.
SUMMARY=$(sdd_stage_summary "$PIPELINE_STATE") || SUMMARY=""
RUNNING_ALL=""
[ -n "$SUMMARY" ] && IFS='|' read -r _ _ RUNNING_ALL _ <<< "$SUMMARY"

# The stage that applies is the MOST DOWNSTREAM running linear stage (within the role's stages when
# there is a role): an upstream stage left in "running" must not switch protection off.
RUNNING_STAGE=""
REQ_CHANGE_RUNNING=0
for s in $RUNNING_ALL; do
  if [ -n "$ROLE" ]; then
    sdd_list_has "$ROLE_STAGES" "$s" || continue
  fi
  if [ "$s" = req-change ]; then REQ_CHANGE_RUNNING=1; continue; fi
  sdd_list_has "$SDD_STAGE_ORDER" "$s" && RUNNING_STAGE="$s"
done

# req-change is the controlled way to modify requirements/ and spec/: while it runs, those writes are
# its own (Art. 4 exception), even if a downstream stage is also marked running.
if [ "$REQ_CHANGE_RUNNING" = 1 ]; then
  case "$REL_PATH" in
    requirements/*|spec/*) exit 0 ;;
  esac
fi

# No running stage = permissive mode
if [ -z "$RUNNING_STAGE" ]; then
  exit 0
fi

# Define prohibited paths per running stage
is_prohibited() {
  local stage="$1"
  local path="$2"
  local tool="$3"

  case "$stage" in
    test-planner)
      case "$path" in
        requirements/*|spec/*|audits/*) return 0 ;;
      esac
      ;;
    plan-architect)
      case "$path" in
        requirements/*|spec/*|audits/*|test/*) return 0 ;;
      esac
      ;;
    task-generator)
      case "$path" in
        requirements/*|spec/*|audits/*|test/*|plan/*) return 0 ;;
      esac
      ;;
    task-implementer)
      case "$path" in
        test/*)
          # test/ declared as code/tests in the SDD Stack Profile (Rails Minitest at repo root):
          # test/models/x_test.rb is implementation; top-level test/*.md docs stay protected.
          sdd_is_impl_path "$path" && return 1
          return 0
          ;;
        requirements/*|spec/*|audits/*|plan/*) return 0 ;;
        task/TASK-FASE-*.md)
          # Allow Edit (checkbox updates), block Write (full overwrite)
          [ "$tool" = "Write" ] && return 0
          ;;
        task/*) return 0 ;;
      esac
      ;;
    # spec-auditor: spec/ is allowed (Mode Fix), but requirements/ is not
    spec-auditor)
      case "$path" in
        requirements/*) return 0 ;;
      esac
      ;;
    # specifications-engineer: requirements/ is not modifiable
    specifications-engineer)
      case "$path" in
        requirements/*) return 0 ;;
      esac
      ;;
    # req-change is lateral: no restrictions (it can touch requirements/ and spec/)
    # requirements-engineer: no upstream to protect
    *)
      return 1
      ;;
  esac

  return 1
}

if is_prohibited "$RUNNING_STAGE" "$REL_PATH" "$TOOL_NAME"; then
  deny "SDD Art. 4 Violation: Stage '$RUNNING_STAGE' cannot modify upstream artifact '$REL_PATH'. Upstream artifacts are immutable during downstream execution. Complete the current stage first, or use sdd-req-change for controlled modifications."
fi

# Not prohibited — allow
exit 0
